# Generated by Django 5.1.4 on 2024-12-08 20:55

from django.db import migrations


def add_units(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Unit = apps.get_model("food_logs", "Unit")
    common_units = [
        {'name': 'grams', 'unit_type': 'weight'},
        {'name': 'kilograms', 'unit_type': 'weight'},
        {'name': 'milliliters', 'unit_type': 'volume'},
        {'name': 'liters', 'unit_type': 'volume'},
        {'name': 'cups', 'unit_type': 'volume'},
        {'name': 'tablespoons', 'unit_type': 'volume'},
        {'name': 'teaspoons', 'unit_type': 'volume'},
        {'name': 'ounces', 'unit_type': 'weight'},
        {'name': 'pounds', 'unit_type': 'weight'},
        {'name': 'pieces', 'unit_type': 'count'},
        {'name': 'slices', 'unit_type': 'count'},
        {'name': 'servings', 'unit_type': 'special'},
    ]
    for unit in common_units:
        Unit.objects.create(**unit)


class Migration(migrations.Migration):

    dependencies = [
        ('food_logs', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_units),
    ]
